apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: approval # Garante que o deployment seja criado no namespace correto
spec:
  replicas: 1 # Ajuste conforme necessário
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend:latest # Substituirá pela tag correta na pipeline
          ports:
            - containerPort: 8080 # Porta da sua API Spring Boot
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service.production:5432/postgres # URL do banco de dados
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: "5235"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
