apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: approval # Garante que o deployment seja criado no namespace correto
spec:
  replicas: 1 # Ajuste conforme necessário
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend:latest # Substituirá pela tag correta na pipeline
          ports:
            - containerPort: 8080 # Porta da sua API Spring Boot
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets # Nome do Secret que contém DATABASE_URL
                  key: DATABASE_URL 
            - name: PGUSER
               valueFrom:
                 secretKeyRef:
                   name: postgres-secrets
                   key: POSTGRES_USER
             - name: PGPASSWORD
               valueFrom:
                 secretKeyRef:
                   name: postgres-secrets
                   key: POSTGRES_PASSWORD
             - name: PGDATABASE
               valueFrom:
                 secretKeyRef:
                   name: postgres-secrets
                   key: POSTGRES_DB
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
