apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: approval # Garante que o deployment seja criado no namespace correto
spec:
  replicas: 1 # Ajuste conforme necessário
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend:latest # Substituirá pela tag correta na pipeline
          ports:
            - containerPort: 8080 # Porta da sua API Spring Boot
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets # Nome do Secret que contém DATABASE_URL
                  key: DATABASE_URL
            # Certifique-se que estes estão alinhados com o '- name: DATABASE_URL' acima
            - name: PGUSER
              valueFrom: # <--- Alinhado com 'valueFrom' acima
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USER
            - name: PGPASSWORD # <--- Alinhado com outros '- name:'
              valueFrom: # <--- Alinhado com outros 'valueFrom:'
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
            - name: PGDATABASE # <--- Alinhado com outros '- name:'
              valueFrom: # <--- Alinhado com outros 'valueFrom:'
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_DB
          # Certifique-se que 'resources' está alinhado com 'env' e 'ports'
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
