apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: approval # ou approval
data:
  DATABASE_URL: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres-service:5432/$(POSTGRES_DB)?sslmode=disable"