name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure gcloud and Install gke-gcloud-auth-plugin
        run: |
          gcloud config set project ${{ secrets.PROJECT_ID }}
          gcloud config set compute/zone us-central1-a
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} --region us-central1
          sudo apt-get update -y
          sudo apt-get install -y kubectl
          gcloud components install kubectl
          gcloud components install gke-gcloud-auth-plugin

      - name: Build and Push Docker Image
        run: |
          DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }} # Define uma variável para facilitar a leitura
          docker build -t $DOCKER_USERNAME/backend:latest -t $DOCKER_USERNAME/backend:${{ github.sha }} .
          docker login -u "$DOCKER_USERNAME" -p ${{ secrets.DOCKER_PASSWORD }} # As aspas garantem que a variável seja expandida corretamente
          docker push $DOCKER_USERNAME/backend:latest
          docker push $DOCKER_USERNAME/backend:${{ github.sha }}

      - name: Deploy to Kubernetes
        run: |
          NAMESPACE=approval # Ou 'frontend'
          DEPLOYMENT_FILE=backend-deployment.yaml # Ou 'backend-deployment.yaml'
          sed -i "s|backend:latest|backend:latest|g" "$DEPLOYMENT_FILE"

          kubectl apply -f "$DEPLOYMENT_FILE" -n approval
          kubectl apply -f backend-service.yaml -n approval # Adapte o nome do arquivo se necessário
          kubectl apply -f configMap.yaml -n approval
