name: Deploy Backend to GKE

on:
  push:
    branches:
      - main  # ou sua branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up GCloud CLI
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker authentication (opcional - se usar Docker Hub)
        if: ${{ secrets.DOCKER_USERNAME != '' && secrets.DOCKER_PASSWORD != '' }}
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image to Artifact Registry
        run: |
          gcloud config set project ${{ secrets.PROJECT_ID }}
          gcloud artifacts repositories create backend-repo --repository-format=docker --location=us-central1 --description="Docker repository for backend images" --if-not-exists
          VERSION=$(echo "$GITHUB_SHA" | cut -c1-7)
          IMAGE_NAME="us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/backend-repo/backend:${VERSION}"
          docker build -t ${IMAGE_NAME} .
          docker push ${IMAGE_NAME}
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} --zone ${{ secrets.GKE_ZONE }} --project ${{ secrets.PROJECT_ID }}

      - name: Apply Kubernetes manifests
        run: |
          sed -i "s|IMAGE_PLACEHOLDER|${{ env.IMAGE_NAME }}|g" k8s/backend-deployment.yaml
          kubectl apply -f k8s/backend-deployment.yaml -n production
          kubectl apply -f k8s/backend-service.yaml -n production